### ISSUE TITLE
does it support multi kyes?

### ISSUE THREAD

**Issue by AICodeHunt** [shellc/aify#2]

**Comment by shellc** [comment]
You can specify your OpenAI key in each YAML file, like this.

```
model: 
    type: llm 
    vendor: openai 
    name: gpt-3.5-turbo 
    params: 
        api_key: sk-xxxxx
```
